### ISSUE TITLE
video frozen?

### ISSUE THREAD

**Issue by bachoo786** [DustinBryant/MMM-Ring#1]
Hi @DustinBryant 

Thanks for this lovely module.

I tried it but I find the video shown is frozen and nothing is moving for 2 mins. Is that a bug?

Thanks.

**Comment by DustinBryant** [comment]
Hey @bachoo786,

It definitely shouldn't be frozen.

There was an update to ring-client-api that went out last night. I haven't had a chance to update on my personal set up yet but I will be able to later today and see if I get the same results.

Another thing to check is with MM open and ready, ring your doorbell and check the MMM-Ring/public folder to see if new .ts files are being dropped in there. This could either be a transcoder issue or an hls (http live streaming) client issue.

Also, are there any errors that appear in the terminal you're running MM from? Or, if you could run "run start dev" for MM do any errors appear in the dev console?

**Comment by bachoo786** [comment]
Hi thanks for your reply

I can confirm that the .ts and .m3u8 files are dropping when the ring doorbell is activated. 

I don't see any errors either

**Comment by DustinBryant** [comment]
Ok, and just to verify. You do have an active paid Ring subscription? I don't think this is the issue since you are getting some stream back, but trying to rule out any possibilities.

**Comment by bachoo786** [comment]
Yes indeed I have an active ring subscription.

I will check again tonight and report back to see if the issue persists.

**Comment by DustinBryant** [comment]
I'll be getting the latest ring-client-api later today and checking myself as well. Though, I highly doubt that is the issue here.

It sounds like it may be an issue with hls if you are getting the .ts files but the video is frozen. I think what is happening is it isn't being told to "play" the stream for you and instead is just showing the first frame of the first video captured.

**Comment by bachoo786** [comment]
Yeah maybe.. how do I resolve the hls issue then?

**Comment by DustinBryant** [comment]
This shouldn't be on your end. I'm going to play with it later today, 

I may just have hls wait for 2nd/3rd file before starting up. It's either it isn't being told to play or it is playing too early where the next video to stream isn't available yet before the first completes. 

I'll let you know.

**Comment by bachoo786** [comment]
Ok mate thanks

**Comment by bachoo786** [comment]
Hey Dustin

So I tried it again and the video doesn't display on my mirror. Earlier I rung the doorbell and I was checking it from my laptop chrome browser as I was at work and away from my magic mirror.

Now that I am home I tried it but surprisingly I don't get anything on my magic mirror.

If I was to check this on a normal computer it works but like I mentioned earlier the video is frozen.. 

Any idea?

**Comment by DustinBryant** [comment]
That's more in line with something I've experienced before. Let me get back to you on this one.

**Comment by bachoo786** [comment]
Ok mate thanks

**Comment by bachoo786** [comment]
Any joy buddy?

**Comment by DustinBryant** [comment]
Still looking into it. I updated ring-client-api to the latest and was unable to re-create the issue you are experiencing. I've attempted to enlist assistance from the person responsible for ring-client-api as they have more experience in the way of ffmpeg and hls.js. 

I may try to lower quality of stream to rule out potential latency issues. Again, I'll have to get back to you.

**Comment by bachoo786** [comment]
Oh right

Ok mate thanks again.

**Comment by bachoo786** [comment]
Hi @DustinBryant 

so I reinstalled the ring module and I see the following:

```
pi@raspberrypi:~/MagicMirror/modules/MMM-Ring $ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/fse                                                     vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                     2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"}                                                     )

added 189 packages from 120 contributors and audited 280 packages in 66.05s
found 0 vulnerabilities
```
not sure if this is an issue or?

**Comment by DustinBryant** [comment]
That dependency isn't necessary for what we're using the ring-client-api for and wouldn't effect anything.

I made some changes on a different branch than master to see if by reducing latency by means of reducing video quality and allowing for more possible gaps/time if we could fix this for you.

Navigate to the MMM-Ring folder and run the following:
git pull && git checkout LowLatencyTesting && npm install

Now once that has completed run MagicMirror again and test if by ringing your doorbell you see the video.

**Comment by bachoo786** [comment]
Ok just tested it..I can now see the  video on my mirror but its frozen. Its showing like a snapshot with no movement whatsoever.

**Comment by DustinBryant** [comment]
Ok, this one is basically my last shot at it. If it doesn't work, unfortunately, I'm just going to have to add a help needed tag and hope someone comes along to fix the issue. This utilizes video tech for encoding and display of streams that I just do not have enough experience in to figure out as it is quite complicating.

With this next change I dropped encoding down to the lowest setting I can get it. I sure hope this works!

Navigate to MMM-Ring and run the following:
git pull

Then run MagicMirror again and test.

**Comment by bachoo786** [comment]
Nope same issue as before video is frozen I am afraid

**Comment by DustinBryant** [comment]
Requesting assistance for those more familiar with streaming video using ffmpeg encoding and hls player for stream.

Posted requesting assistance in the MM forums:
https://forum.magicmirror.builders/topic/11147/video-encoding-ffmpeg-and-streaming-hls

**Comment by DustinBryant** [comment]
Reflecting back on this issue. It made me realize I may have attacked it from the wrong angle. If you see the video is frozen that probably means the video isn't being played.

By chance are you running Magic Mirror in Server Only and using your own browser to serve it up? If so, you'll need to find a setting/flag in the browser for autoplay-policy and set it to no-user-gesture-required.

If you aren't running it in Server Only then make sure you update the MagicMirror software. Someone made a nice script that makes this easy.
https://forum.magicmirror.builders/topic/10859/new-update-upgrade-script-ready-for-testing

If this fixes your issue, I suggest changing the MMM-Ring back to the master branch. You can do that by navigating to the /MagicMirror/modules/MMM-Ring folder and in terminal running the following command:
```
git checkout master && git pull && npm install
```

**Comment by bachoo786** [comment]
Hey

So I am running mm on my rpi 3b and I can access it from my mobile or any other browser on my laptop. On my rpi it automatically runs when the rpi boots up. So I suppose its server mode.

One thing I noticed with your ring module is that if I was to access my mm on chrome on my laptop then the video works fine and doesn't freezes. However on my rpi the video is frozen. 

I haven't updated my mm since the beginning of 2018 I think as I had issues with the updates I.e. I used to get a black screen on my rpi which made me downgrade to the working version of mm which what I am using now i.e. 2.7.1

**Comment by DustinBryant** [comment]
Ahh, ok now this makes more sense.

If you're worried about updating the MagicMirror you don't technically have to. Though, the script I provided from the forums really does work and I haven't seen it break anything. If you decide not to update your Magic Mirror you'll need to add a line into a file in the source code. If you do this, then the MMM-Ring should work properly on your rpi.

Edit this file:
```/MagicMirror/js/electron.js```

Look for this line: 
```js
function createWindow() {
```

Immediately after that line put this line:
```js
app.commandLine.appendSwitch("autoplay-policy", "no-user-gesture-required");
```

Should look like this:
```js
function createWindow() {
	app.commandLine.appendSwitch("autoplay-policy", "no-user-gesture-required");
```

After you've made the change then save the file. Restart MagicMirror and it should work for you.

Let me know how it goes!

**Comment by bachoo786** [comment]
hey @DustinBryant 

it worked :) works perfectly on my MM with no frozen video.

thanks alot man.

**Comment by bachoo786** [comment]
@DustinBryant quick question buddy: are you saying the ring module on my MM (on my RPI browser) was frozen because I had to do the changes to the /MagicMirror/js/electron.js file?

Because i have other modules which do not update on my MM (on my RPI browser)? Would the changes to the /MagicMirror/js/electron.js file solve the issues with my other modules too? 

Thanks.

**Comment by DustinBryant** [comment]
Technically, yes. It basically allows the browser within electron to auto-play or programmatically play video when it's needed.

As for the other modules I can't speak for them. If they use some type of video then it probably could have fixed those as well.

MM had an update earlier this year that set that in code. You're now basically doing that manually instead.

**Comment by bachoo786** [comment]
Thanks.

So I wanted to report that I could hear the sound from my ring doorbell as I have a speaker connected to my raspberry.

I also have a mic connected to my raspberry but unfortunately the person outside couldn't hear me. I guess the ring api doesn't allow 2 way communication.

**Comment by DustinBryant** [comment]
Correct, it will not do 2 way communication.
