### ISSUE TITLE
Module didn't anything

### ISSUE THREAD

**Issue by eberhorst** [DustinBryant/MMM-Ring#12]
Hello

the installation has worked so far, and the 2FA has also created a token, but as soon as I press the bell nothing happens at the mirror!

Is it possible that the module can't handle 2 bells in one account?

thanks

**Comment by jasonbade** [comment]
I too have two Ring doorbells and can't get it to work.

**Comment by Doudy** [comment]
> Hello
> 
> the installation has worked so far, and the 2FA has also created a token, but as soon as I press the bell nothing happens at the mirror!

> thanks

Idem for me
I have the stream.ts file at \home\pi\MagicMirror\modules\MMM-Ring\public\
But nothing at screen !

**Comment by Doudy** [comment]
Hello,
Yesterday I did several tests.
My MMM with only as module:
Alert + clock + ring = ring display OK
Alert + clock + ring + weatherforecast = ring display OK
Alert + clock + ring + weatherforecast + newsfeed = ring display OK
Alert + clock + ring + weatherforecast + newsfeed + MMM-CalendarExt2 = ring display OK
Alert + clock + ring + weatherforecast + newsfeed + MMM-CalendarExt2 + MMM-Domoticz = ring display OK
If I add MMM-SmartWebDisplay = ring display NOK
If I add MMM-Buienradar = ring display NOK

An idea ?

**Comment by eberhorst** [comment]
I have now reduced my account to 1 doorbell and completely rebuilt the MagicMirror (With MagicMirror OS)

During the installation I had to install npm additionally and update Nodejs, because the OS only had the v10 installed.
I updated Node to v14...

And it still does not work!
I can't even get the .ts file in the public folder 

I get the following message with "npm install":
audited 188 packages in 8,911s

4 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by DustinBryant** [comment]
Just pushed a new update that may or may not help. The Ring-client npm developer is about to release a change that will fix possible NAT issues and once that happens it may fix some of the issues you all are experiencing.

For the time being, please update by navigating to the MMM-Ring directory within MagicMirror/modules and perform the following:

```git pull```
```npm install```

Ring now requires Two-Factor Authentication so please make sure to follow this Wiki on the details of setting that up correctly: https://github.com/DustinBryant/MMM-Ring/wiki/Refresh-Tokens

The biggest difference in change is the module now automatically gets a new Refresh Token for you when the one you provide expires.

**Comment by eberhorst** [comment]
Thanks for your effort :-)

I have done the update now and I don't get a .ts file in the public folder!

I see that the login with the 2FA works, because the rings in the app were accepted on the mobile phone, and I didn't accept them!

**Comment by DustinBryant** [comment]
Worth a shot at least. The developer of the Ring-client this module uses has his changes in beta version 2 right now. It seems he's working on it very actively and hopefully we'll have a new release. I don't want to point this module to a beta library just yet so I'll wait for him to release it officially and once that happens I'll update this module which hopefully takes care of all the issues.

**Comment by DustinBryant** [comment]
The ring-client-api has now been updated to 9.1.1 and the biggest feature of that upgrade is:

> UPnP and NAT-PMP hole punching has been removed in favor of RTP latching. This should lead to a successful live stream, regardless of network configuration, network settings, and NAT type

Please update MMM-Ring to the latest and let me know if this fixes your issues:

```git pull```
```npm install```

**Comment by eberhorst** [comment]
Hello

It works perfectly now!
Update and renew the sFA token!

Afterwards everything worked fine!

thanks again!
