### ISSUE TITLE
Minutes to stream video issue

### ISSUE THREAD

**Issue by aacmsu** [DustinBryant/MMM-Ring#2]
Is there a specific way to format ringMinutesToStreamVideo? The video continues to stream after any given int. Also, the Ring itself continues to circle its blue light indicating the doorbell is still ringing.

**Comment by DustinBryant** [comment]
The format is a decimal value. So if you wanted 1 1/2 minutes you'd set the ringMinutesToStreamVideo value to: **1.5**

More specifically, it takes that decimal value and converts it to milliseconds with this formula:
milliseconds = value * 60 * 1000

In the case of 1.5 as the value we'd get a return of 90000 milliseconds or 90 seconds.

By the way, I updated a couple days ago and actually set the default down to 1.5 from 2. I did find 2 minutes to be a little too much time.

You can update by navigating to MagicMirror/modules/MMM-Ring and running the following command:
```
git pull && npm install
```

As for the blue light indication on the doorbell itself. It stays active for the length of time you set for the ringMinutesToStreamVideo. If an error occurs, internet drops, or MagicMirror application isn't shut down properly it may leave that light on for some time. I've only ever experienced it do this for 5 minutes at most. If everything is working properly it should only keep it active for the length of ringMinutesToStreamVideo.

**Comment by aacmsu** [comment]
Same issue, I have tried different 0.5, 1.0 and 1.5 but no change. The video continued streaming for about 15 minutes after ringing the doorbell.

**Comment by DustinBryant** [comment]
Can you post your config here with username/password redacted?

**Comment by aacmsu** [comment]
{
      module: 'MMM-Ring',
      position: 'middle_center',
      config: {
      ringEmail: '',
      ringPwd: '',
      ringMinutesToStreamVideo: 0.05,
      ringVideoWidth: '800'
      }
    },

In this current config, I am using 0.05, according to testing this should give me 30sec of video.

**Comment by DustinBryant** [comment]
Accidentally introduced this bug with a recent previous commit. It's now fixed and all you should need to do is update.

You can update by navigating to MagicMirror/modules/MMM-Ring and running the following command:
```
git pull && npm install
```

Also, **0.05** would actually only be for 3 seconds. If you want 30 seconds then place **0.5** in its place.
