### ISSUE TITLE
Can't Get Stream from Ring Doorbell Pro to Showup on MagicMirror, But Stream from Ring Floodlight Cam Works Great

### ISSUE THREAD

**Issue by VJRasbPi** [DustinBryant/MMM-Ring#21]
I'm having a strange problem. I have 2 Ring devices: a Video Doorbell Pro and a Floodlight Cam. Both work perfectly using the Ring App so I know there is no hardware failure. I have MMM-Ring configured to send video when motion occurs. The Floodlight Cam works perfectly. When motion is detected the video pops-up on MagicMirror and displays for 1 minute and 30 seconds as defined by default. I check the 'public' folder under the MMM-Ring directory and I see multiple streamxx.ts files of various sizes (where xx are sequential numbers) as well as a stream.m3u8 file. I verify the activity in the terminal session and everything occurs as expected:

- [2020-11-20 14:48:26.359] [LOG]    MMM-Ring at (11/20/2020, 2:48:26 PM): Deck has sensed motion Preparing video stream.
- [2020-11-20 14:49:57.034] [LOG]    MMM-Ring at (11/20/2020, 2:49:57 PM): timeout hit
- [2020-11-20 14:49:57.037] [LOG]    MMM-Ring at (11/20/2020, 2:49:57 PM): Deck video stream has ended

The problem is with the Video Doorbell Pro. It doesn't matter if it's motion detected or the doorbell is pressed, I have the same issue, no video appears in MagicMirror. I check the 'public' folder under the MMM-Ring directory and I see a single stream0.ts file with a size of 0 bytes as well as a stream.m3u8 file (about have the size of when the deck cam stream worked. I check the terminal sequence and I see that the video stream is ending approx 20 seconds after the 'detection' occurs and then the scheduled 'timeout' happens 1:30 after the detection:

- [2020-11-20 13:47:51.064] [LOG]    MMM-Ring at (11/20/2020, 1:47:51 PM): Front Door has sensed motion Preparing video stream.
- [2020-11-20 13:48:11.435] [LOG]    MMM-Ring at (11/20/2020, 1:48:11 PM): Front Door video stream has ended
- [2020-11-20 13:49:21.343] [LOG]    MMM-Ring at (11/20/2020, 1:49:21 PM): timeout hit

I see no errors in the terminal when MagicMirror is booting up, It detects both of the devices and indicates that all is ready to go other than it repeats that it actively listening for doorbell presses and motion events, but that may be because there are 2 devices:

- [2020-11-20 12:55:10.343] [LOG]    MMM-Ring at (11/20/2020, 12:55:10 PM): Refresh Token Updated
- [2020-11-20 12:55:11.425] [LOG]    MMM-Ring at (11/20/2020, 12:55:11 PM): Found 1 location(s) with 2 camera(s).
- [2020-11-20 12:55:11.430] [LOG]    MMM-Ring at (11/20/2020, 12:55:11 PM): Location xxxx has the following 2 camera(s):
- [2020-11-20 12:55:11.431] [LOG]    MMM-Ring at (11/20/2020, 12:55:11 PM): - yyyyyyyyy: Front Door (lpd_v2)
- [2020-11-20 12:55:11.432] [LOG]    MMM-Ring at (11/20/2020, 12:55:11 PM): - zzzzzzzzz: Deck (floodlight_v2)
- [2020-11-20 12:55:11.433] [LOG]    MMM-Ring at (11/20/2020, 12:55:11 PM): Location xxxx has the following 0 device(s):
- [2020-11-20 12:55:11.434] [LOG]    MMM-Ring at (11/20/2020, 12:55:11 PM): Actively listening for doorbell presses
- [2020-11-20 12:55:11.436] [LOG]    MMM-Ring at (11/20/2020, 12:55:11 PM): Actively listening for Motion events
- [2020-11-20 12:55:11.437] [LOG]    MMM-Ring at (11/20/2020, 12:55:11 PM): Actively listening for doorbell presses
- [2020-11-20 12:55:11.439] [LOG]    MMM-Ring at (11/20/2020, 12:55:11 PM): Actively listening for Motion events

There are no MMM-Ring errors when I strt MagicMirror using the 'npm start dev' command. As a matter of fact the only error at all is the **"Electron Security Warning (Insecure Resources) This renderer process loads resources using insecure protocols."** warning because it recommends using HTTPS as opposed to HTTP. (I'm not sure how to fix that).

Re: my set-up, I'm running MagicMirror ver 2.13.0 on a RasbPi 4 2Gb board (manually installed, not via script). I have the following modules installed, configured and running: alert, updatenotification, clock, calendar (listing US Holidays), currentweather, weatherforecast, MMM-Ring, MMM-BackgroundSlideshow and MMM-ImagesPhotos. 

Based on a previous post, here is other info you may be looking for:

- Do you have an active Ring subscription (must have an active Ring subscription)? **Yes**
- What version of the MagicMirror are you running? **Ver 2.13.0**
- How are you running MagicMirror (Normal, Server Only, Client Only, or Docker)? **Normal**
- Are there any errors posted to the terminal (with MagicMirror running, minimize it [Alt, then Ctrl +m], and look at the terminal from which you started MagicMirror)? **No errors other than doorbell streaming ending early, before timeout**
- Are there any errors on the dev console (with the terminal, navigate to the MagicMirror folder and run npm start dev) **No, just Electron security concern**
- Can you provide your config for MMM-Ring (with username/password redacted)
**{
module: "MMM-Ring",
position: "bottom_center",
config: {
ring2faRefreshToken: redacted
ringMinutesToStreamVideo: "1.5",
ringVideoWidth: "800",
ringStreamMotion: "true",
}
},**
- Are .ts files being created? **As described above, a single Stream0.ts file is created (size = 0 bytes)**

Out of desperation I even tried calling RING and described the problem to them. Surprisingly they asked me to confirm that I was using version 2.13.0 of MagicMirror, so they were aware of the App and the module. They had me reconfig the Doorbell to the network but that didn't resolve the issue. They told me they were going to refer the issue to their 'advanced' troubleshooting Team, but I haven't heard anything back yet.

Any ideas, assistance would be greatly appreciated. I love this module, but really need the doorbell to work to make it 100% productive.

Thanks for your continued support of this module.

**Comment by DustinBryant** [comment]
Hey @VJRasbPi , if I could help I totally would! I no longer have any RING devices so I can't really test out any changes or fixes. I thought @Cpaczek was going to take over the code changes but they've seem to have disappeared. I know the unofficial RING API has had several updates so it could just be as simple as having that updated, but again, I have no way to confirm that.

If someone else comes along and wants to contribute to this I'm all for it.

**Comment by cpaczek** [comment]
I appoligize I have been busy with school but I will look into this right now. It seems to still work fine with my ring doorbell but I will see if updating the API will fix it.

**Comment by cpaczek** [comment]
@VJRasbPi if you manually update the ring api package does work? `npm update`

**Comment by VJRasbPi** [comment]
**Thanks @Cpaczek, that did the trick!**  Among a variety of things updated by issuing the "npm update" from the MMM-Ring directory, the "ring-client-api" was updated to **ver 9.12.6**.  Looking into the version history of the "ring-client-api" _(by browsing closed issues found at https://github.com/dgreif/ring)_ It looks like some camera problems started happening in the September/October time frame (something to do with new Media servers at Ring???) and the issues were resolved with release of ver 9.12.0.

The MMM-Ring Module is incredible! Thank You @DustinBryant for creating the module and Thank You @Cpaczek for supporting it!
