### ISSUE TITLE
decrease delay before showing video

### ISSUE THREAD

**Issue by mdissel** [DustinBryant/MMM-Ring#8]
Is it possible (or normal?) that the delay is about 10 seconds before the video is shown after pressing the ring button?

ps. Thanks for this very handy module!

**Comment by steampunk85** [comment]
Also would like to know if the delay can be reduced. Ill most likely have answered the door by the time the video shows up

**Comment by Doudy** [comment]
> Also would like to know if the delay can be reduced.

Same for me

**Comment by Doudy** [comment]
nobody ?

**Comment by DustinBryant** [comment]
The delay is an issue with Ring and not a result of this module. There are no artificial delays put in place here. The amount of time it is taking to get a video is about the exact amount of time Ring provides it back.
