### ISSUE TITLE
Refresh Token Error

### ISSUE THREAD

**Issue by electromitter** [DustinBryant/MMM-Ring#9]
can anybody help me with this error?

0|MagicMirror  | [2020-04-25 17:19:54.904] [ERROR]  
0|MagicMirror  | (node:23600) UnhandledPromiseRejectionWarning: Error: Failed to fetch oauth token from Ring. Verify that your refresh token is correct. invalid_grant
0|MagicMirror  |     at RingRestClient.<anonymous> (/home/pi/MagicMirror/modules/MMM-Ring/node_modules/ring-client-api/lib/api/rest-client.js:129:23)
0|MagicMirror  |     at Generator.throw (<anonymous>)
0|MagicMirror  |     at rejected (/home/pi/MagicMirror/modules/MMM-Ring/node_modules/ring-client-api/lib/api/rest-client.js:6:65)
0|MagicMirror  |     at processTicksAndRejections (internal/process/task_queues.js:89:5)
0|MagicMirror  | [2020-04-25 17:19:54.912] [ERROR]  
0|MagicMirror  | (node:23600) UnhandledPromiseRejectionWarning: Error: Failed to fetch oauth token from Ring. Verify that your refresh token is correct. invalid_grant
0|MagicMirror  |     at RingRestClient.<anonymous> (/home/pi/MagicMirror/modules/MMM-Ring/node_modules/ring-client-api/lib/api/rest-client.js:129:23)
0|MagicMirror  |     at Generator.throw (<anonymous>)
0|MagicMirror  |     at rejected (/home/pi/MagicMirror/modules/MMM-Ring/node_modules/ring-client-api/lib/api/rest-client.js:6:65)
0|MagicMirror  |     at processTicksAndRejections (internal/process/task_queues.js:89:5)
0|MagicMirror  | [2020-04-25 17:19:54.920] [ERROR]  
0|MagicMirror  | (node:23600) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
0|MagicMirror  | [2020-04-25 17:19:54.923] [ERROR]  (node:23600) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
0|MagicMirror  | [2020-04-25 17:19:54.925] [ERROR]  (node:23600) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
0|MagicMirror  | [2020-04-25 17:19:54.927] [ERROR]  (node:23600) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jasonbade** [comment]
Make sure you use "ring2faRefreshToken" in your config and not the output of the auth script.

**Comment by electromitter** [comment]
thanks that helps
